//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticTac1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticgame
    {
        public int S_No { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public Nullable<int> Score { get; set; }
    }
}
